# Tmux
brew "tmux"

# jq, a command line JSON editor
brew "jq"

# Docker image layer inspector
brew "dive"

# Maven
brew "maven"

# Go
brew "go"

# gh - GitHub command-line
brew "gh"

# direnv - Load/unload env vars based on PWD
brew "direnv"
